In [12]:
import numpy as np

arr=[[1,2,3,4],[5,7,8,9]]
numpy_array=np.array(arr)
print(f"Original array:{arr}")
print(f"Numpy array: {numpy_array}")
result=numpy_array*2
print(f"reslut: {result}")
# for row in numpy_array:
#     print(row)
#     for r in row:
#         print(r)




Original array:[[1, 2, 3, 4], [5, 7, 8, 9]]
Numpy array: [[1 2 3 4]
 [5 7 8 9]]
reslut: [[ 2  4  6  8]
 [10 14 16 18]]


In [1]:
import numpy as np
one_d_array=np.array([1,2,3,4,5,6])
print(one_d_array)
three_d_array=np.array([[1,2,3],[4,5,6],[7,8,9],[12,34,56]])
arr_dim=three_d_array.ndim
print(f"Number of dimensision:{arr_dim}")
# print(f"Number of shapes :{three_d_array.shape}")
# print(three_d_array)
# zeros_array=np.zeros((3,3), dtype=int)
# ones_array=np.ones([2,5], dtype =int)
# print("arrays with normal shape")
# print(ones_array)
# print(zeros_array)
# print("arrays witn updated or reshaped :")
# print(one_d_array.reshape(2,3))

# array slicing: 
arr = np.array([10,20,30,40,50])
new =np.arange(12).reshape(3,4)
print(new)
print(new[0:2, 1:2])
print(arr[0:3])





[1 2 3 4 5 6]
Number of dimensision:2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1]
 [5]]
[10 20 30]


In [2]:
reshaped_array=np.arange(16).reshape(4,4)
print(reshaped_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [25]:
# Intermidate level
# Filtering
arr=np.array([3,7,2,9,12,5])
print(arr[arr>5])
# using comprehension
result=[int(x) for x in arr if x>5]
print(result)
even=[int(x) for x in arr if x%2 ==0]
print(even)
# Mathematical operations
arr=np.array([1,2,3,4,5])
arr_new=arr+10
mul_arr=arr*3
square_arr=arr**2
# print(f"Square every element{square_arr}")
# print(f"multiplicaitioresult: {mul_arr} ")
# print(arr_new)
# Statics 
stat_arr=np.array([4,8,15, 16, 23,42])
mean=stat_arr.mean()
max_value=stat_arr.max()
devaition =stat_arr.std()
print(max_value)
print(devaition)
print(mean)

[ 7  9 12]
[7, 9, 12]
[2, 12]
42
12.315302134607444
18.0


In [29]:
matrix_test=np.array([[1,2,3],
                      [4,5,6]])
print(f"2D array test{matrix_test}")
for row in matrix_test:
    for i in row:
        if i==5:
            print(f"5 found at {matrix_test[i]}")

2D array test[[1 2 3]
 [4 5 6]]


IndexError: index 5 is out of bounds for axis 0 with size 2